server:
  port: 9090
spring:
  application:
    name: admin-server
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
admin-login-service:
  url: http://localhost:8080