server:
  port: 9090
spring:
  application:
    name: admin-server
  security:
    user:
      name: stxtory
      password: 11dnjf3dlf#
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/