spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database: postgresql
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: bion_user
    password: 0xoavf78NKtWENO5Ui7bFCGZoGCoaTWG
