spring:
  application:
    name: dev
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: 
  h2:
    console:
      enabled: true
      path: /h2
