server:
  port: 8085

spring:
  application:
    name: edge-server
  cloud:
    gateway:
      routes:
      - id: trade-service
        uri: lb://trade-service
        predicates:
        - Path=/trade-service/**
      - id: admin-server
        uri: lb://admin-server
        predicates:
        - Path=/admin-server/**        
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    logfile:
      access: read-only